FROM python:3.7.3-stretch

COPY django_example /src/
RUN pip install -r /src/requirements.txt

COPY prometheus_redis_client /package/prometheus_redis_client/prometheus_redis_client
COPY setup.py /package/prometheus_redis_client/setup.py
WORKDIR /package/prometheus_redis_client/
RUN python setup.py sdist
RUN pip install /package/prometheus_redis_client/dist/*

WORKDIR /src/

CMD PROMETHEUS_REDIS_URI=redis://redis:6379 python manage.py runserver 0.0.0.0:8000